### ISSUE TITLE
Freezing at "Using /home/user/.cache/torch_extensions as PyTorch extensions root..."

### ISSUE THREAD

**Issue by mallorbc** [Xirider/finetune-gpt2xl#10]
After installing the dependencies and running the given commands to fine-tune a model, some GPU VRAM is allocated(looking at nvidia-smi) , but then the program seems to just stop with once "Using /home/user/.cache/torch_extensions as PyTorch extensions root..." prints

**Comment by Xirider** [comment]
I will re-test the script and report back.

**Comment by Xirider** [comment]
On a fresh server everything seems fine for me. Your message usually comes right before cpu_adam is set, therefore your cpu might be incompatible with Deepspeed (i.e. many AMD CPUs) or you don't have enough system RAM (at lest 60 GB for GPT2-xl and 78 GB for GPT-NEO).

**Comment by mallorbc** [comment]
Thanks for the response. I am trying to use an RTX 3090, a Ryzen 3600 and 64 GB of Ram. Could you please elaborate more on your environment and maybe leave a yml file of it(if using conda), as you are using more than what is in the requirements.txt file.

**Comment by mallorbc** [comment]
I found the issue.  I was installing DeepSpeed, but for whatever reason, the needed dependencies inside of DeepSpeed were not installed.  Installing for source fixed this issue.
